const ALDRIN_SWAP_PROGRAM_ID = "AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6";
const ALDRIN_SWAP_V2_PROGRAM_ID =
  "CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4";
const BALANSOL_PROGRAM_ID = "D3BBjqUdCYuP18fNvvMbPAZ8DpcRi4io2EsYHQawJDag";
const CREMA_PROGRAM_ID = "CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR";
const CYKURA_PROGRAM_ID = "cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8";
const DRADEX_PROGRAM_ID = "dp2waEWSBy5yKmq65ergoU3G6qRLmqa6K7We4rZSKph";
const DELTA_FI_PROGRAM_ID = "GNExJhNUhc9LN2DauuQAUJnXoy6DJ6zey3t9kT9A2PF3";
const GOOSE_FX_PROGRAM_ID = "7WduLbRfYhTJktjLw5FDEyrqoEv61aTTCuGAetgLjzN5";
const INVARIANT_PROGRAM_ID = "HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt";
const LIFINITY_V2_PROGRAM_ID = "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c";
const MARCO_POLO_PROGRAM_ID = "9tKE7Mbmj4mxDjWatikzGAtkoWosiiZX9y6J4Hfm2R8H";
const MERCURIAL_SWAP_PROGRAM_ID = "MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky";
const METEORA_PROGRAM_ID = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB";
const METEORA_VAULT_PROGRAM_ID = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi";
const OPENBOOK_PROGRAM_ID = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX";
const RAYDIUM_CLMM_PROGRAM_ID = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK";
const PHOENIX_PROGRAM_ID = "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY";
const RAYDIUM_AMM_V4_PROGRAM_ID =
  "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8";
const SAROS_PROGRAM_ID = "SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr";
const SENCHA_PROGRAM_ID = "SCHAtsf8mbjyjiv4LkhLKutTf6JnZAbdJKFkXQNMFHZ";
const MAINNET_SERUM_DEX_PROGRAM =
  "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin";
const STEPN_PROGRAM_ID = "Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j";
const SYMMETRY_PROGRAM_ID = "2KehYt3KsEQR53jYcxjbQp2d2kCp4AkuQW68atufRwSr";
const WHIRLPOOL_PROGRAM_ID = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc";

const ALL_PROGRAM_IDS = [
  ALDRIN_SWAP_PROGRAM_ID,
  ALDRIN_SWAP_V2_PROGRAM_ID,
  BALANSOL_PROGRAM_ID,
  CREMA_PROGRAM_ID,
  CYKURA_PROGRAM_ID,
  DRADEX_PROGRAM_ID,
  DELTA_FI_PROGRAM_ID,
  GOOSE_FX_PROGRAM_ID,
  INVARIANT_PROGRAM_ID,
  LIFINITY_V2_PROGRAM_ID,
  MARCO_POLO_PROGRAM_ID,
  MERCURIAL_SWAP_PROGRAM_ID,
  METEORA_PROGRAM_ID,
  METEORA_VAULT_PROGRAM_ID,
  OPENBOOK_PROGRAM_ID,
  RAYDIUM_CLMM_PROGRAM_ID,
  PHOENIX_PROGRAM_ID,
  RAYDIUM_AMM_V4_PROGRAM_ID,
  SAROS_PROGRAM_ID,
  SENCHA_PROGRAM_ID,
  MAINNET_SERUM_DEX_PROGRAM,
  STEPN_PROGRAM_ID,
  SYMMETRY_PROGRAM_ID,
  WHIRLPOOL_PROGRAM_ID,
];

module.exports = { ALL_PROGRAM_IDS };
